#
# MovieGraph from Neo4j demo
# how to run: bin/spark-submit --packages graphframes:graphframes:0.6.0-spark2.3-s_2.11 movieGraph.py
#
from pyspark.sql import SparkSession, Row
from pyspark.sql.functions import col
from graphframes import *

spark = SparkSession.builder \
                    .master("local") \
                    .appName("MovieGraph") \
                    .getOrCreate()

nodes = [
    {"id":'TheMatrix', "label":["MOVIE"], "name":'The Matrix', "released":1999, "tagline":'Welcome to the Real World'},
    {"id":'TheMatrixReloaded', "label":["MOVIE"], "name":'The Matrix Releaded', "released":2003, "tagline":'Free your mind'},
    {"id":'TheMatrixRevolutions', "label":["MOVIE"], "name":'The Matrix Revolutions', "released":2003, "tagline":'Everything that has a beginning has an end'},
    {"id":'TheDevilsAdvocate', "label":["MOVIE"], "name":"The Devil's Advocate", "released":1997, "tagline":'Evil has its winning ways'},
    {"id":'AFewGoodMen', "label":["MOVIE"], "name":"A Few Good Men", "released":1992, "tagline":"In the heart of the nation's capital, in a courthouse of the U.S. government, one man will stop at nothing to keep his honor, and one will stop at nothing to find the truth."},
    {"id":'TopGun', "label":["MOVIE"], "name":"Top Gun", "released":1986, "tagline":'I feel the need, the need for speed.'},
    {"id":'JerryMaguire', "label":["MOVIE"], "name":"Jerry Maguire", "released":2000, "tagline":'The rest of his life begins now.'},
    {"id":'StandByMe', "label":["MOVIE"], "name":"Stand By Me", "released":1986, "tagline":"For some, it's the last real taste of innocence, and the first real taste of life. But for everyone, it's the time that memories are made of."},
    {"id":'AsGoodAsItGets', "label":["MOVIE"], "name":"As Good as It Gets", "released":1997, "tagline":'A comedy from the heart that goes for the throat.'},
    {"id":'WhatDreamsMayCome', "label":["MOVIE"], "name":"What Dreams May Come", "released":1998, "tagline":'After life there is more. The end is just the beginning.'},
    {"id":'SnowFallingonCedars', "label":["MOVIE"], "name":"Snow Falling on Cedars", "released":1999, "tagline":'First loves last. Forever.'},
    {"id":'YouveGotMail', "label":["MOVIE"], "name":"You've Got Mail", "released":1998, "tagline":'At odds in life... in love on-line.'},
    {"id":'SleeplessInSeattle', "label":["MOVIE"], "name":"Sleepless in Seattle", "released":1993, "tagline":'What if someone you never met, someone you never saw, someone you never knew was the only someone for you?'},
    {"id":'JoeVersustheVolcano', "label":["MOVIE"], "name":'Joe Versus the Volcano', "released":1990, "tagline":'A story of love, lava and burning desire.'},
    {"id":'WhenHarryMetSally', "label":["MOVIE"], "name":'When Harry Met Sally', "released":1998, "tagline":'Can two friends sleep together and still love each other in the morning?'},
    {"id":'ThatThingYouDo', "label":["MOVIE"], "name":'That Thing You Do', "released":1996, "tagline":'In every life there comes a time when that thing you dream becomes that thing you do'},
    {"id":'TheReplacements', "label":["MOVIE"], "name":'The Replacements', "released":2000, "tagline":'Pain heals, Chicks dig scars... Glory lasts forever'},
    {"id":'RescueDawn', "label":["MOVIE"], "name":'RescueDawn', "released":2006, "tagline":"Based on the extraordinary true story of one man's fight for freedom"},
    {"id":'TheBirdcage', "label":["MOVIE"], "name":'The Birdcage', "released":1996, "tagline":'Come as you are'},
    {"id":'Unforgiven', "label":["MOVIE"], "name":'Unforgiven', "released":1992, "tagline":"It's a hell of a thing, killing a man"},
    {"id":'JohnnyMnemonic', "label":["MOVIE"], "name":'Frost/Nixon', "released":1995, "tagline":'The hottest data on earth. In the coolest head in town'},
    {"id":'CloudAtlas', "label":["MOVIE"], "name":'Cloud Atlas', "released":2012, "tagline":'Everything is connected'},
    {"id":'TheDaVinciCode', "label":["MOVIE"], "name":'The Da Vinci Code', "released":2006, "tagline":'Break The Codes'},
    {"id":'VforVendetta', "label":["MOVIE"], "name":'V for Vendetta', "released":2006, "tagline":'Freedom! Forever!'},
    {"id":'SpeedRacer', "label":["MOVIE"], "name":'Speed Racer', "released":2008, "tagline":'Speed has no limits'},
    {"id":'NinjaAssassin', "label":["MOVIE"], "name":'Ninja Assassin', "released":2009, "tagline":'Prepare to enter a secret world of assassins'},
    {"id":'TheGreenMile', "label":["MOVIE"], "name":'The Green Mile', "released":1999, "tagline":"Walk a mile you'll never forget."},
    {"id":'FrostNixon', "label":["MOVIE"], "name":'Ninja Assassin', "released":2008, "tagline":'400 million people were waiting for the truth.'},
    {"id":'Hoffa', "label":["MOVIE"], "name":'Hoffa', "released":1992, "tagline":"He didn't want law. He wanted justice."},
    {"id":'Apollo13', "label":["MOVIE"], "name":'Apollo 13', "released":1995, "tagline":'Houston, we have a problem.'},
    {"id":'Twister', "label":["MOVIE"], "name":'Twister', "released":1996, "tagline":"Don't Breathe. Don't Look Back."},
    {"id":'CastAway', "label":["MOVIE"], "name":'Cast Away', "released":2000, "tagline":'At the edge of the world, his journey begins.'},
    {"id":'OneFlewOvertheCuckoosNest', "label":["MOVIE"], "name":"One Flew Over the Cuckoo's Nest", "released":1975, "tagline":"If he's crazy, what does that make you?"},
    {"id":'SomethingsGottaGive', "label":["MOVIE"], "name":"Something's Gotta Give", "released":2003, "tagline":'At the edge of the world, his journey begins.'},
    {"id":'BicentennialMan', "label":["MOVIE"], "name":"Bicentennial Man", "released":1999, "tagline":"One robot's 200 year journey to become an ordinary man."},
    {"id":'CharlieWilsonsWar', "label":["MOVIE"], "name":"Charlie Wilson's War", "released":2007, "tagline":"A stiff drink. A little mascara. A lot of nerve. Who said they couldn't bring down the Soviet empire."},
    {"id":'ThePolarExpress', "label":["MOVIE"], "name":"The Polar Express", "released":2004, "tagline":'This Holiday Season… Believe'},
    {"id":'ALeagueofTheirOwn', "label":["MOVIE"], "name":"A League of Their Own", "released":1992, "tagline":'Once in a lifetime you get a chance to do something different.'},
    {"id":'Keanu', "label":["Person"], "name":'Keanu Reeves', "born":1964},
    {"id":'Carrie', "label":["Person"], "name":'Carrie-Anne Moss', "born":1967},
    {"id":'Laurence', "label":["Person"], "name":'Laurence Fishburne', "born":1961},
    {"id":'Hugo', "label":["Person"], "name":'Hugo Weaving', "born":1960},
    {"id":'LillyW', "label":["Person"], "name":'Lilly Wachowski', "born":1967},
    {"id":'LanaW', "label":["Person"], "name":'Lana Wachowski', "born":1965},
    {"id":'JoelS', "label":["Person"], "name":'Joel Silver', "born":1952},
    {"id":'Emil', "label":["Person"], "name":'Emil Eifrem', "born":1978},
    {"id":'Charlize', "label":["Person"], "name":'Charlize Theron', "born":1975},
    {"id":'Al', "label":["Person"], "name":'Al Pacino', "born":1940},
    {"id":'Taylor', "label":["Person"], "name":'Taylor Hackford', "born":1944},
    {"id":'TomC', "label":["Person"], "name":'Tom Cruise', "born":1962},
    {"id":'JackN', "label":["Person"], "name":'Jack Nicholson', "born":1937},
    {"id":'DemiM', "label":["Person"], "name":'Demi Moore', "born":1962},
    {"id":'KevinB', "label":["Person"], "name":'Kevin Bacon', "born":1958},
    {"id":'KieferS', "label":["Person"], "name":'Kiefer Sutherland', "born":1966},
    {"id":'NoahW', "label":["Person"], "name":'Noah Wyle', "born":1971},
    {"id":'CubaG', "label":["Person"], "name":'Cuba Gooding Jr.', "born":1968},
    {"id":'KevinP', "label":["Person"], "name":'Kevin Pollak', "born":1957},
    {"id":'JTW', "label":["Person"], "name":'J.T. Walsh', "born":1943},
    {"id":'JamesM', "label":["Person"], "name":'James Marshall', "born":1967},
    {"id":'ChristopherG', "label":["Person"], "name":'Christopher Guest', "born":1948},
    {"id":'RobR', "label":["Person"], "name":'Rob Reiner', "born":1947},
    {"id":'AaronS', "label":["Person"], "name":'Aaron Sorkin', "born":1961},
    {"id":'KellyM', "label":["Person"], "name":'Kelly McGillis', "born":1957},
    {"id":'ValK', "label":["Person"], "name":'Val Kilmer', "born":1959},
    {"id":'AnthonyE', "label":["Person"], "name":'Anthony Edwards', "born":1962},
    {"id":'TomS', "label":["Person"], "name":'Tom Skerritt', "born":1933},
    {"id":'MegR', "label":["Person"], "name":'Meg Ryan', "born":1961},
    {"id":'TonyS', "label":["Person"], "name":'Tony Scott', "born":1944},
    {"id":'JimC', "label":["Person"], "name":'Jim Cash', "born":1941},
    {"id":'ReneeZ', "label":["Person"], "name":'Renee Zellweger', "born":1969},
    {"id":'KellyP', "label":["Person"], "name":'Kelly Preston', "born":1962},
    {"id":'JerryO', "label":["Person"], "name":"Jerry O'Connell", "born":1974},
    {"id":'JayM', "label":["Person"], "name":'Jay Mohr', "born":1970},
    {"id":'BonnieH', "label":["Person"], "name":'Bonnie Hunt', "born":1961},
    {"id":'ReginaK', "label":["Person"], "name":'Regina King', "born":1971},
    {"id":'JonathanL', "label":["Person"], "name":'Jonathan Lipnicki', "born":1996},
    {"id":'CameronC', "label":["Person"], "name":'Cameron Crowe', "born":1957},
    {"id":'RiverP', "label":["Person"], "name":'River Phoenix', "born":1970},
    {"id":'CoreyF', "label":["Person"], "name":'Corey Feldman', "born":1971},
    {"id":'WilW', "label":["Person"], "name":'Wil Wheaton', "born":1972},
    {"id":'JohnC', "label":["Person"], "name":'John Cusack', "born":1966},
    {"id":'MarshallB', "label":["Person"], "name":'Marshall Bell', "born":1942},
    {"id":'HelenH', "label":["Person"], "name":'Helen Hunt', "born":1963},
    {"id":'GregK', "label":["Person"], "name":'Greg Kinnear', "born":1963},
    {"id":'JamesB', "label":["Person"], "name":'James L. Brooks', "born":1940},
    {"id":'AnnabellaS', "label":["Person"], "name":'Annabella Sciorra', "born":1960},
    {"id":'MaxS', "label":["Person"], "name":'Max von Sydow', "born":1929},
    {"id":'WernerH', "label":["Person"], "name":'Werner Herzog', "born":1942},
    {"id":'Robin', "label":["Person"], "name":'Robin Williams', "born":1951},
    {"id":'VincentW', "label":["Person"], "name":'Vincent Ward', "born":1956},
    {"id":'EthanH', "label":["Person"], "name":'Ethan Hawke', "born":1970},
    {"id":'RickY', "label":["Person"], "name":'Rick Yune', "born":1971},
    {"id":'JamesC', "label":["Person"], "name":'James Cromwell', "born":1940},
    {"id":'ScottH', "label":["Person"], "name":'Scott Hicks', "born":1953},
    {"id":'ParkerP', "label":["Person"], "name":'Parker Posey', "born":1968},
    {"id":'DaveC', "label":["Person"], "name":'Dave Chappelle', "born":1973},
    {"id":'SteveZ', "label":["Person"], "name":'Steve Zahn', "born":1967},
    {"id":'TomH', "label":["Person"], "name":'Tom Hanks', "born":1956},
    {"id":'NoraE', "label":["Person"], "name":'Nora Ephron', "born":1941},
    {"id":'RitaW', "label":["Person"], "name":'Rita Wilson', "born":1956},
    {"id":'BillPull', "label":["Person"], "name":'Bill Pullman', "born":1953},
    {"id":'VictorG', "label":["Person"], "name":'Victor Garber', "born":1949},
    {"id":'RosieO', "label":["Person"], "name":"Rosie O'Donnell", "born":1962},
    {"id":'JohnS', "label":["Person"], "name":"John Patrick Stanley", "born":1950},
    {"id":'Nathan', "label":["Person"], "name":"Nathan Lane", "born":1956},
    {"id":'BillyC', "label":["Person"], "name":"Billy Crystal", "born":1948},
    {"id":'CarrieF', "label":["Person"], "name":"Carrie Fisher", "born":1956},
    {"id":'BrunoK', "label":["Person"], "name":"Bruno Kirby", "born":1949},
    {"id":'LivT', "label":["Person"], "name":"Liv Tyler", "born":1977},
    {"id":'Brooke', "label":["Person"], "name":"Brooke Langton", "born":1970},
    {"id":'Gene', "label":["Person"], "name":"Gene Hackman", "born":1930},
    {"id":'Orlando', "label":["Person"], "name":"Orlando Jones", "born":1968},
    {"id":'Howard', "label":["Person"], "name":"Howard Deutch", "born":1950},
    {"id":'ChristianB', "label":["Person"], "name":"Christian Bale", "born":1974},
    {"id":'ZachG', "label":["Person"], "name":"Zach Grenier", "born":1954},
    {"id":'MikeN', "label":["Person"], "name":"Mike Nichols", "born":1931},
    {"id":'RichardH', "label":["Person"], "name":"Richard Harris", "born":1930},
    {"id":'ClintE', "label":["Person"], "name":"Clint Eastwood", "born":1930},
    {"id":'Takeshi', "label":["Person"], "name":"Takeshi Kitano", "born":1947},
    {"id":'Dina', "label":["Person"], "name":"Dina Meyer", "born":1968},
    {"id":'IceT', "label":["Person"], "name":"Ice-T", "born":1958},
    {"id":'RobertL', "label":["Person"], "name":"Robert Longo", "born":1953},
    {"id":'HalleB', "label":["Person"], "name":"Halle Berry", "born":1966},
    {"id":'JimB', "label":["Person"], "name":"Jim Broadbent", "born":1949},
    {"id":'TomT', "label":["Person"], "name":"Tom Tykwer", "born":1965},
    {"id":'DavidMitchell', "label":["Person"], "name":"David Mitchell", "born":1969},
    {"id":'StefanArndt', "label":["Person"], "name":"Stefan Arndt", "born":1961},
    {"id":'IanM', "label":["Person"], "name":"Ian McKellen", "born":1939},
    {"id":'AudreyT', "label":["Person"], "name":"Audrey Tautou", "born":1976},
    {"id":'PaulB', "label":["Person"], "name":"Paul Bettany", "born":1971},
    {"id":'RonH', "label":["Person"], "name":"Ron Howard", "born":1954},
    {"id":'NatalieP', "label":["Person"], "name":"Natalie Portman", "born":1981},
    {"id":'StephenR', "label":["Person"], "name":"Stephen Rea", "born":1946},
    {"id":'JohnH', "label":["Person"], "name":"John Hurt", "born":1940},
    {"id":'BenM', "label":["Person"], "name":"Ben Miles", "born":1967},
    {"id":'EmileH', "label":["Person"], "name":"Emile Hirsch", "born":1985},
    {"id":'JohnG', "label":["Person"], "name":"John Goodman", "born":1960},
    {"id":'SusanS', "label":["Person"], "name":"Susan Sarandon", "born":1946},
    {"id":'MatthewF', "label":["Person"], "name":"Matthew Fox", "born":1966},
    {"id":'ChristinaR', "label":["Person"], "name":"Christina Ricci", "born":1966},
    {"id":'Rain', "label":["Person"], "name":"Rain", "born":1982},
    {"id":'NaomieH', "label":["Person"], "name":"Naomie Harris"},
    {"id":'MichaelD', "label":["Person"], "name":"Michael Clarke Duncan", "born":1957},
    {"id":'DavidM', "label":["Person"], "name":"David Morse", "born":1953},
    {"id":'SamR', "label":["Person"], "name":"Sam Rockwell", "born":1968},
    {"id":'GaryS', "label":["Person"], "name":"Gary Sinise", "born":1955},
    {"id":'PatriciaC', "label":["Person"], "name":"Patricia Clarkson", "born":1959},
    {"id":'FrankD', "label":["Person"], "name":"Frank Darabont", "born":1959},
    {"id":'FrankL', "label":["Person"], "name":"Frank Langella", "born":1938},
    {"id":'MichaelS', "label":["Person"], "name":"Michael Sheen", "born":1969},
    {"id":'OliverP', "label":["Person"], "name":"Oliver Platt", "born":1960},
    {"id":'DannyD', "label":["Person"], "name":"Danny DeVito", "born":1944},
    {"id":'JohnR', "label":["Person"], "name":"John C. Reilly", "born":1960},
    {"id":'EdH', "label":["Person"], "name":"Ed Harris", "born":1950},
    {"id":'BillPax', "label":["Person"], "name":"Bill Paxton", "born":1955},
    {"id":'PhilipH', "label":["Person"], "name":"Philip Seymour Hoffman", "born":1967},
    {"id":'JanB', "label":["Person"], "name":"Jan de Bont", "born":1943},
    {"id":'RobertZ', "label":["Person"], "name":"Robert Zemeckis", "born":1951},
    {"id":'MilosF', "label":["Person"], "name":"Milos Forman", "born":1932},
    {"id":'DianeK', "label":["Person"], "name":"Diane Keaton", "born":1946},
    {"id":'NancyM', "label":["Person"], "name":"Nancy Meyers", "born":1949},
    {"id":'ChrisC', "label":["Person"], "name":"Chris Columbus", "born":1958},
    {"id":'JuliaR', "label":["Person"], "name":"Julia Roberts", "born":1967},
    {"id":'Madonna', "label":["Person"], "name":"Madonna", "born":1954},
    {"id":'GeenaD', "label":["Person"], "name":"Geena Davis", "born":1956},
    {"id":'LoriP', "label":["Person"], "name":"Lori Petty", "born":1963},
    {"id":'PennyM', "label":["Person"], "name":"Penny Marshall", "born":1943},
    {"id":'PaulBlythe', "label":["Person"], "name":"Paul Blythe"},
    {"id":'AngelaScope', "label":["Person"], "name":"Angela Scope"},
    {"id":'JessicaThompson', "label":["Person"], "name":"Jessica Thompson"},
    {"id":'JamesThompson', "label":["Person"], "name":"James Thompson"},
]

edges = [
    {"src":'Keanu', "dst":'TheMatrix', "type":["ACTED_IN"], "roles":['Neo']},
    {"src":'Carrie', "dst":'TheMatrix', "type":["ACTED_IN"], "roles":['Trinity']},
    {"src":'Laurence', "dst":'TheMatrix', "type":["ACTED_IN"], "roles":['Morpheus']},
    {"src":'Hugo', "dst":'TheMatrix', "type":["ACTED_IN"], "roles":['Agent Smith']},
    {"src":'Emil', "dst":'TheMatrix', "type":["ACTED_IN"], "roles":['Emil']},
    {"src":'LillyW', "dst":'TheMatrix', "type":["DIRECTED"]},
    {"src":'LanaW', "dst":'TheMatrix', "type":["DIRECTED"]},
    {"src":'JoelS', "dst":'TheMatrix', "type":["PRODUCED"]},
    {"src":'Keanu', "dst":'TheMatrixReloaded', "type":["ACTED_IN"], "roles":['Neo']},
    {"src":'Carrie', "dst":'TheMatrixReloaded', "type":["ACTED_IN"], "roles":['Trinity']},
    {"src":'Laurence', "dst":'TheMatrixReloaded', "type":["ACTED_IN"], "roles":['Morpheus']},
    {"src":'Hugo', "dst":'TheMatrixReloaded', "type":["ACTED_IN"], "roles":['Agent Smith']},
    {"src":'LillyW', "dst":'TheMatrixReloaded', "type":["DIRECTED"]},
    {"src":'LanaW', "dst":'TheMatrixReloaded', "type":["DIRECTED"]},
    {"src":'JoelS', "dst":'TheMatrixReloaded', "type":["PRODUCED"]},
    {"src":'Keanu', "dst":'TheMatrixRevolutions', "type":["ACTED_IN"], "roles":['Neo']},
    {"src":'Carrie', "dst":'TheMatrixRevolutions', "type":["ACTED_IN"], "roles":['Trinity']},
    {"src":'Laurence', "dst":'TheMatrixRevolutions', "type":["ACTED_IN"], "roles":['Morpheus']},
    {"src":'Hugo', "dst":'TheMatrixRevolutions', "type":["ACTED_IN"], "roles":['Agent Smith']},
    {"src":'LillyW', "dst":'TheMatrixRevolutions', "type":["DIRECTED"]},
    {"src":'LanaW', "dst":'TheMatrixRevolutions', "type":["DIRECTED"]},
    {"src":'JoelS', "dst":'TheMatrixRevolutions', "type":["PRODUCED"]},
    {"src":'Keanu', "dst":'TheDevilsAdvocate', "type":["ACTED_IN"], "roles":['Kevin Lomax']},
    {"src":'Charlize', "dst":'TheDevilsAdvocate', "type":["ACTED_IN"], "roles":['Mary Ann Lomax']},
    {"src":'Al', "dst":'TheDevilsAdvocate', "type":["ACTED_IN"], "roles":['John Milton']},
    {"src":'Taylor', "dst":'TheDevilsAdvocate', "type":["DIRECTED"]},
    {"src":'TomC', "dst":'AFewGoodMen', "type":["ACTED_IN"], "roles":['Lt. Daniel Kaffee']},
    {"src":'JackN', "dst":'AFewGoodMen', "type":["ACTED_IN"], "roles":['Col. Nathan R. Jessup']},
    {"src":'DemiM', "dst":'AFewGoodMen', "type":["ACTED_IN"], "roles":['Lt. Cdr. JoAnne Galloway']},
    {"src":'KevinB', "dst":'AFewGoodMen', "type":["ACTED_IN"], "roles":['Capt. Jack Ross']},
    {"src":'KieferS', "dst":'AFewGoodMen', "type":["ACTED_IN"], "roles":['Lt. Jonathan Kendrick']},
    {"src":'NoahW', "dst":'AFewGoodMen', "type":["ACTED_IN"], "roles":['Cpl. Jeffrey Barnes']},
    {"src":'CubaG', "dst":'AFewGoodMen', "type":["ACTED_IN"], "roles":['Cpl. Carl Hammaker']},
    {"src":'KevinP', "dst":'AFewGoodMen', "type":["ACTED_IN"], "roles":['Lt. Sam Weinberg']},
    {"src":'JTW', "dst":'AFewGoodMen', "type":["ACTED_IN"], "roles":['Lt. Col. Matthew Andrew Markinson']},
    {"src":'JamesM', "dst":'AFewGoodMen', "type":["ACTED_IN"], "roles":['Pfc. Louden Downey']},
    {"src":'ChristopherG', "dst":'AFewGoodMen', "type":["ACTED_IN"], "roles":['Dr. Stone']},
    {"src":'AaronS', "dst":'AFewGoodMen', "type":["ACTED_IN"], "roles":['Man in Bar']},
    {"src":'RobR', "dst":'TheDevilsAdvocate', "type":["DIRECTED"]},
    {"src":'AaronS', "dst":'TheDevilsAdvocate', "type":["WROTE"]},
    {"src":'TomC', "dst":'TopGun', "type":["ACTED_IN"], "roles":['Maverick']},
    {"src":'KellyM', "dst":'TopGun', "type":["ACTED_IN"], "roles":['Charlie']},
    {"src":'ValK', "dst":'TopGun', "type":["ACTED_IN"], "roles":['Iceman']},
    {"src":'AnthonyE', "dst":'TopGun', "type":["ACTED_IN"], "roles":['Goose']},
    {"src":'TomS', "dst":'TopGun', "type":["ACTED_IN"], "roles":['Viper']},
    {"src":'MegR', "dst":'TopGun', "type":["ACTED_IN"], "roles":['Carole']},
    {"src":'TonyS', "dst":'TopGun', "type":["DIRECTED"]},
    {"src":'JimC', "dst":'TopGun', "type":["WROTE"]},
    {"src":'TomC', "dst":'JerryMaguire', "type":["ACTED_IN"], "roles":['Jerry Maguire']},
    {"src":'CubaG', "dst":'JerryMaguire', "type":["ACTED_IN"], "roles":['Rod Tidwell']},
    {"src":'ReneeZ', "dst":'JerryMaguire', "type":["ACTED_IN"], "roles":['Dorothy Boyd']},
    {"src":'KellyP', "dst":'JerryMaguire', "type":["ACTED_IN"], "roles":['Avery Bishop']},
    {"src":'JerryO', "dst":'JerryMaguire', "type":["ACTED_IN"], "roles":['Frank Cushman']},
    {"src":'JayM', "dst":'JerryMaguire', "type":["ACTED_IN"], "roles":['Bob Sugar']},
    {"src":'BonnieH', "dst":'JerryMaguire', "type":["ACTED_IN"], "roles":['Laurel Boyd']},
    {"src":'ReginaK', "dst":'JerryMaguire', "type":["ACTED_IN"], "roles":['Marcee Tidwell']},
    {"src":'JonathanL', "dst":'JerryMaguire', "type":["ACTED_IN"], "roles":['Ray Boyd']},
    {"src":'CameronC', "dst":'JerryMaguire', "type":["DIRECTED"]},
    {"src":'CameronC', "dst":'JerryMaguire', "type":["PRODUCED"]},
    {"src":'CameronC', "dst":'JerryMaguire', "type":["WROTE"]},
    {"src":'WilW', "dst":'StandByMe', "type":["ACTED_IN"], "roles":['Gordie Lachance']},
    {"src":'RiverP', "dst":'StandByMe', "type":["ACTED_IN"], "roles":['Chris Chambers']},
    {"src":'JerryO', "dst":'StandByMe', "type":["ACTED_IN"], "roles":['Vern Tessio']},
    {"src":'CoreyF', "dst":'StandByMe', "type":["ACTED_IN"], "roles":['Teddy Duchamp']},
    {"src":'JohnC', "dst":'StandByMe', "type":["ACTED_IN"], "roles":['Denny Lachance']},
    {"src":'KieferS', "dst":'StandByMe', "type":["ACTED_IN"], "roles":['Ace Merrill']},
    {"src":'MarshallB', "dst":'StandByMe', "type":["ACTED_IN"], "roles":['Mr. Lachance']},
    {"src":'RobR', "dst":'StandByMe', "type":["DIRECTED"]},
    {"src":'JackN', "dst":'AsGoodAsItGets', "type":["ACTED_IN"], "roles":['Melvin Udall']},
    {"src":'HelenH', "dst":'AsGoodAsItGets', "type":["ACTED_IN"], "roles":['Carol Connelly']},
    {"src":'GregK', "dst":'AsGoodAsItGets', "type":["ACTED_IN"], "roles":['Simon Bishop']},
    {"src":'CubaG', "dst":'AsGoodAsItGets', "type":["ACTED_IN"], "roles":['Frank Sachs']},
    {"src":'JamesB', "dst":'AsGoodAsItGets', "type":["DIRECTED"]},
    {"src":'Robin', "dst":'WhatDreamsMayCome', "type":["ACTED_IN"], "roles":['Chris Nielsen']},
    {"src":'CubaG', "dst":'WhatDreamsMayCome', "type":["ACTED_IN"], "roles":['Albert Lewis']},
    {"src":'AnnabellaS', "dst":'WhatDreamsMayCome', "type":["ACTED_IN"], "roles":['Annie Collins-Nielsen']},
    {"src":'MaxS', "dst":'WhatDreamsMayCome', "type":["ACTED_IN"], "roles":['The Tracker']},
    {"src":'WernerH', "dst":'WhatDreamsMayCome', "type":["ACTED_IN"], "roles":['The Face']},
    {"src":'VincentW', "dst":'WhatDreamsMayCome', "type":["DIRECTED"]},
    {"src":'EthanH', "dst":'SnowFallingonCedars', "type":["ACTED_IN"], "roles":['Ishmael Chambers']},
    {"src":'RickY', "dst":'SnowFallingonCedars', "type":["ACTED_IN"], "roles":['Kazuo Miyamoto']},
    {"src":'MaxS', "dst":'SnowFallingonCedars', "type":["ACTED_IN"], "roles":['Nels Gudmundsson']},
    {"src":'JamesC', "dst":'SnowFallingonCedars', "type":["ACTED_IN"], "roles":['Judge Fielding']},
    {"src":'ScottH', "dst":'SnowFallingonCedars', "type":["DIRECTED"]},
    {"src":'TomH', "dst":'YouveGotMail', "type":["ACTED_IN"], "roles":['Joe Fox']},
    {"src":'MegR', "dst":'YouveGotMail', "type":["ACTED_IN"], "roles":['Kathleen Kelly']},
    {"src":'GregK', "dst":'YouveGotMail', "type":["ACTED_IN"], "roles":['Frank Navasky']},
    {"src":'ParkerP', "dst":'YouveGotMail', "type":["ACTED_IN"], "roles":['Patricia Eden']},
    {"src":'DaveC', "dst":'YouveGotMail', "type":["ACTED_IN"], "roles":['Kevin Jackson']},
    {"src":'SteveZ', "dst":'YouveGotMail', "type":["ACTED_IN"], "roles":['George Pappas']},
    {"src":'NoraE', "dst":'YouveGotMail', "type":["DIRECTED"]},
    {"src":'TomH', "dst":'SleeplessInSeattle', "type":["ACTED_IN"], "roles":['Sam Baldwin']},
    {"src":'MegR', "dst":'SleeplessInSeattle', "type":["ACTED_IN"], "roles":['Annie Reed']},
    {"src":'RitaW', "dst":'SleeplessInSeattle', "type":["ACTED_IN"], "roles":['Suzy']},
    {"src":'BillPull', "dst":'SleeplessInSeattle', "type":["ACTED_IN"], "roles":['Walter']},
    {"src":'VictorG', "dst":'SleeplessInSeattle', "type":["ACTED_IN"], "roles":['Greg']},
    {"src":'RosieO', "dst":'SleeplessInSeattle', "type":["ACTED_IN"], "roles":['Becky']},
    {"src":'NoraE', "dst":'SleeplessInSeattle', "type":["DIRECTED"]},
    {"src":'TomH', "dst":'JoeVersustheVolcano', "type":["ACTED_IN"], "roles":['Joe Banks']},
    {"src":'MegR', "dst":'JoeVersustheVolcano', "type":["ACTED_IN"], "roles":['DeDe', 'Angelica Graynamore', 'Patricia Graynamore']},
    {"src":'Nathan', "dst":'JoeVersustheVolcano', "type":["ACTED_IN"], "roles":['Baw']},
    {"src":'JohnS', "dst":'JoeVersustheVolcano', "type":["DIRECTED"]},
    {"src":'BillyC', "dst":'WhenHarryMetSally', "type":["ACTED_IN"], "roles":['Harry Burns']},
    {"src":'MegR', "dst":'WhenHarryMetSally', "type":["ACTED_IN"], "roles":['Sally Albright']},
    {"src":'CarrieF', "dst":'WhenHarryMetSally', "type":["ACTED_IN"], "roles":['Marie']},
    {"src":'BrunoK', "dst":'WhenHarryMetSally', "type":["ACTED_IN"], "roles":['Jess']},
    {"src":'RobR', "dst":'WhenHarryMetSally', "type":["DIRECTED"]},
    {"src":'RobR', "dst":'WhenHarryMetSally', "type":["PRODUCED"]},
    {"src":'NoraE', "dst":'WhenHarryMetSally', "type":["PRODUCED"]},
    {"src":'NoraE', "dst":'WhenHarryMetSally', "type":["WROTE"]},
    {"src":'TomH', "dst":'ThatThingYouDo', "type":["ACTED_IN"], "roles":['Mr. White']},
    {"src":'LivT', "dst":'ThatThingYouDo', "type":["ACTED_IN"], "roles":['Faye Dolan']},
    {"src":'Charlize', "dst":'ThatThingYouDo', "type":["ACTED_IN"], "roles":['Tina']},
    {"src":'TomH', "dst":'ThatThingYouDo', "type":["DIRECTED"]},
    {"src":'Keanu', "dst":'TheReplacements', "type":["ACTED_IN"], "roles":['Shane Falco']},
    {"src":'Brooke', "dst":'TheReplacements', "type":["ACTED_IN"], "roles":['Annabelle Farrell']},
    {"src":'Gene', "dst":'TheReplacements', "type":["ACTED_IN"], "roles":['Jimmy McGinty']},
    {"src":'Orlando', "dst":'TheReplacements', "type":["ACTED_IN"], "roles":['Clifford Franklin']},
    {"src":'Howard', "dst":'TheReplacements', "type":["DIRECTED"]},
    {"src":'MarshallB', "dst":'RescueDawn', "type":["ACTED_IN"], "roles":['Admiral']},
    {"src":'ChristianB', "dst":'RescueDawn', "type":["ACTED_IN"], "roles":['Dieter Dengler']},
    {"src":'ZachG', "dst":'RescueDawn', "type":["ACTED_IN"], "roles":['Squad Leader']},
    {"src":'SteveZ', "dst":'RescueDawn', "type":["ACTED_IN"], "roles":['Duane']},
    {"src":'Howard', "dst":'RescueDawn', "type":["DIRECTED"]},
    {"src":'Robin', "dst":'TheBirdcage', "type":["ACTED_IN"], "roles":['Armand Goldman']},
    {"src":'Nathan', "dst":'TheBirdcage', "type":["ACTED_IN"], "roles":['Albert Goldman']},
    {"src":'Gene', "dst":'TheBirdcage', "type":["ACTED_IN"], "roles":['Sen. Kevin Keeley']},
    {"src":'MikeN', "dst":'TheBirdcage', "type":["DIRECTED"]},
    {"src":'RichardH', "dst":'Unforgiven', "type":["ACTED_IN"], "roles":['English Bob']},
    {"src":'ClintE', "dst":'Unforgiven', "type":["ACTED_IN"], "roles":['Bill Munny']},
    {"src":'Gene', "dst":'Unforgiven', "type":["ACTED_IN"], "roles":['Little Bill Daggett']},
    {"src":'ClintE', "dst":'Unforgiven', "type":["DIRECTED"]},
    {"src":'Keanu', "dst":'JohnnyMnemonic', "type":["ACTED_IN"], "roles":['Johnny Mnemonic']},
    {"src":'Takeshi', "dst":'JohnnyMnemonic', "type":["ACTED_IN"], "roles":['Takahashi']},
    {"src":'Dina', "dst":'JohnnyMnemonic', "type":["ACTED_IN"], "roles":['Jane']},
    {"src":'IceT', "dst":'JohnnyMnemonic', "type":["ACTED_IN"], "roles":['J-Bone']},
    {"src":'RobertL', "dst":'JohnnyMnemonic', "type":["DIRECTED"]},
    {"src":'TomH', "dst":'CloudAtlas', "type":["ACTED_IN"], "roles":['Zachry', 'Dr. Henry Goose', 'Isaac Sachs', 'Dermot Hoggins']},
    {"src":'Hugo', "dst":'CloudAtlas', "type":["ACTED_IN"], "roles":['Bill Smoke', 'Haskell Moore', 'Tadeusz Kesselring', 'Nurse Noakes', 'Boardman Mephi', 'Old Georgie']},
    {"src":'HalleB', "dst":'CloudAtlas', "type":["ACTED_IN"], "roles":['Luisa Rey', 'Jocasta Ayrs', 'Ovid', 'Meronym']},
    {"src":'JimB', "dst":'CloudAtlas', "type":["ACTED_IN"], "roles":['Vyvyan Ayrs', 'Captain Molyneux', 'Timothy Cavendish']},
    {"src":'TomT', "dst":'CloudAtlas', "type":["DIRECTED"]},
    {"src":'LillyW', "dst":'CloudAtlas', "type":["DIRECTED"]},
    {"src":'LanaW', "dst":'CloudAtlas', "type":["DIRECTED"]},
    {"src":'StefanArndt', "dst":'CloudAtlas', "type":["PRODUCED"]},
    {"src":'DavidMitchell', "dst":'CloudAtlas', "type":["WROTE"]},
    {"src":'TomH', "dst":'TheDaVinciCode', "type":["ACTED_IN"], "roles":['Dr. Robert Langdon']},
    {"src":'IanM', "dst":'TheDaVinciCode', "type":["ACTED_IN"], "roles":['Sir Leight Teabing']},
    {"src":'AudreyT', "dst":'TheDaVinciCode', "type":["ACTED_IN"], "roles":['Sophie Neveu']},
    {"src":'PaulB', "dst":'TheDaVinciCode', "type":["ACTED_IN"], "roles":['Silas']},
    {"src":'RonH', "dst":'TheDaVinciCode', "type":["DIRECTED"]},
    {"src":'Hugo', "dst":'VforVendetta', "type":["ACTED_IN"], "roles":['V']},
    {"src":'NatalieP', "dst":'VforVendetta', "type":["ACTED_IN"], "roles":['Evey Hammond']},
    {"src":'StephenR', "dst":'VforVendetta', "type":["ACTED_IN"], "roles":['Eric Finch']},
    {"src":'JohnH', "dst":'VforVendetta', "type":["ACTED_IN"], "roles":['High Chancellor Adam Sutler']},
    {"src":'BenM', "dst":'VforVendetta', "type":["ACTED_IN"], "roles":['Dascomb']},
    {"src":'JamesM', "dst":'VforVendetta', "type":["DIRECTED"]},
    {"src":'LillyW', "dst":'VforVendetta', "type":["PRODUCED"]},
    {"src":'LanaW', "dst":'VforVendetta', "type":["PRODUCED"]},
    {"src":'JoelS', "dst":'VforVendetta', "type":["PRODUCED"]},
    {"src":'LillyW', "dst":'VforVendetta', "type":["WROTE"]},
    {"src":'LanaW', "dst":'VforVendetta', "type":["WROTE"]},
    {"src":'EmileH', "dst":'SpeedRacer', "type":["ACTED_IN"], "roles":['Speed Racer']},
    {"src":'JohnG', "dst":'SpeedRacer', "type":["ACTED_IN"], "roles":['Pops']},
    {"src":'SusanS', "dst":'SpeedRacer', "type":["ACTED_IN"], "roles":['Mom']},
    {"src":'MatthewF', "dst":'SpeedRacer', "type":["ACTED_IN"], "roles":['Racer X']},
    {"src":'ChristinaR', "dst":'SpeedRacer', "type":["ACTED_IN"], "roles":['Trixie']},
    {"src":'Rain', "dst":'SpeedRacer', "type":["ACTED_IN"], "roles":['Taejo Togokahn']},
    {"src":'BenM', "dst":'SpeedRacer', "type":["ACTED_IN"], "roles":['Cass Jones']},
    {"src":'LillyW', "dst":'SpeedRacer', "type":["DIRECTED"]},
    {"src":'LanaW', "dst":'SpeedRacer', "type":["DIRECTED"]},
    {"src":'JoelS', "dst":'SpeedRacer', "type":["PRODUCED"]},
    {"src":'LillyW', "dst":'SpeedRacer', "type":["WROTE"]},
    {"src":'LanaW', "dst":'SpeedRacer', "type":["WROTE"]},
    {"src":'Rain', "dst":'NinjaAssassin', "type":["ACTED_IN"], "roles":['Raizo']},
    {"src":'NaomieH', "dst":'NinjaAssassin', "type":["ACTED_IN"], "roles":['Mika Coretti']},
    {"src":'RickY', "dst":'NinjaAssassin', "type":["ACTED_IN"], "roles":['Takeshi']},
    {"src":'BenM', "dst":'NinjaAssassin', "type":["ACTED_IN"], "roles":['Ryan Maslow']},
    {"src":'JamesM', "dst":'NinjaAssassin', "type":["DIRECTED"]},
    {"src":'LillyW', "dst":'NinjaAssassin', "type":["PRODUCED"]},
    {"src":'LanaW', "dst":'NinjaAssassin', "type":["PRODUCED"]},
    {"src":'JoelS', "dst":'SpeedRacer', "type":["PRODUCED"]},
    {"src":'TomH', "dst":'TheGreenMile', "type":["ACTED_IN"], "roles":['Paul Edgecomb']},
    {"src":'MichaelD', "dst":'TheGreenMile', "type":["ACTED_IN"], "roles":['John Coffey']},
    {"src":'DavidM', "dst":'TheGreenMile', "type":["ACTED_IN"], "roles":['Brutus "Brutal" Howell']},
    {"src":'BonnieH', "dst":'TheGreenMile', "type":["ACTED_IN"], "roles":['Jan Edgecomb']},
    {"src":'JamesC', "dst":'TheGreenMile', "type":["ACTED_IN"], "roles":['Warden Hal Moores']},
    {"src":'SamR', "dst":'TheGreenMile', "type":["ACTED_IN"], "roles":['"Wild Bill" Wharton']},
    {"src":'GaryS', "dst":'TheGreenMile', "type":["ACTED_IN"], "roles":['Burt Hammersmith']},
    {"src":'PatriciaC', "dst":'TheGreenMile', "type":["ACTED_IN"], "roles":['Melinda Moores']},
    {"src":'FrankD', "dst":'TheGreenMile', "type":["DIRECTED"]},
    {"src":'FrankL', "dst":'FrostNixon', "type":["ACTED_IN"], "roles":['Richard Nixon']},
    {"src":'MichaelS', "dst":'FrostNixon', "type":["ACTED_IN"], "roles":['David Frost']},
    {"src":'KevinB', "dst":'FrostNixon', "type":["ACTED_IN"], "roles":['Jack Brennan']},
    {"src":'OliverP', "dst":'FrostNixon', "type":["ACTED_IN"], "roles":['Bob Zelnick']},
    {"src":'SamR', "dst":'FrostNixon', "type":["ACTED_IN"], "roles":['James Reston, Jr.']},
    {"src":'RonH', "dst":'FrostNixon', "type":["DIRECTED"]},
    {"src":'JackN', "dst":'Hoffa', "type":["ACTED_IN"], "roles":['Hoffa']},
    {"src":'DannyD', "dst":'Hoffa', "type":["ACTED_IN"], "roles":['Robert "Bobby" Ciaro']},
    {"src":'JTW', "dst":'Hoffa', "type":["ACTED_IN"], "roles":['Frank Fitzsimmons']},
    {"src":'JohnR', "dst":'Hoffa', "type":["ACTED_IN"], "roles":['Peter "Pete" Connelly']},
    {"src":'DannyD', "dst":'Hoffa', "type":["DIRECTED"]},
    {"src":'TomH', "dst":'Apollo13', "type":["ACTED_IN"], "roles":['Jim Lovell']},
    {"src":'KevinB', "dst":'Apollo13', "type":["ACTED_IN"], "roles":['Jack Swigert']},
    {"src":'EdH', "dst":'Apollo13', "type":["ACTED_IN"], "roles":['Gene Kranz']},
    {"src":'BillPax', "dst":'Apollo13', "type":["ACTED_IN"], "roles":['Fred Haise']},
    {"src":'GaryS', "dst":'Apollo13', "type":["ACTED_IN"], "roles":['Ken Mattingly']},
    {"src":'RonH', "dst":'Apollo13', "type":["DIRECTED"]},
    {"src":'BillPax', "dst":'Twister', "type":["ACTED_IN"], "roles":['Bill Harding']},
    {"src":'HelenH', "dst":'Twister', "type":["ACTED_IN"], "roles":['Dr. Jo Harding']},
    {"src":'ZachG', "dst":'Twister', "type":["ACTED_IN"], "roles":['Eddie']},
    {"src":'PhilipH', "dst":'Twister', "type":["ACTED_IN"], "roles":['Dustin "Dusty" Davis']},
    {"src":'JanB', "dst":'Twister', "type":["DIRECTED"]},
    {"src":'TomH', "dst":'CastAway', "type":["ACTED_IN"], "roles":['Chuck Noland']},
    {"src":'HelenH', "dst":'CastAway', "type":["ACTED_IN"], "roles":['Kelly Frears']},
    {"src":'RobertZ', "dst":'CastAway', "type":["DIRECTED"]},
    {"src":'JackN', "dst":'OneFlewOvertheCuckoosNest', "type":["ACTED_IN"], "roles":['Randle McMurphy']},
    {"src":'DannyD', "dst":'OneFlewOvertheCuckoosNest', "type":["ACTED_IN"], "roles":['Martini']},
    {"src":'MilosF', "dst":'OneFlewOvertheCuckoosNest', "type":["DIRECTED"]},
    {"src":'JackN', "dst":'SomethingsGottaGive', "type":["ACTED_IN"], "roles":['Harry Sanborn']},
    {"src":'DianeK', "dst":'SomethingsGottaGive', "type":["ACTED_IN"], "roles":['Erica Barry']},
    {"src":'Keanu', "dst":'SomethingsGottaGive', "type":["ACTED_IN"], "roles":['Julian Mercer']},
    {"src":'NancyM', "dst":'SomethingsGottaGive', "type":["DIRECTED"]},
    {"src":'NancyM', "dst":'SomethingsGottaGive', "type":["PRODUCED"]},
    {"src":'NancyM', "dst":'SomethingsGottaGive', "type":["WROTE"]},
    {"src":'Robin', "dst":'BicentennialMan', "type":["ACTED_IN"], "roles":['Andrew Marin']},
    {"src":'OliverP', "dst":'BicentennialMan', "type":["ACTED_IN"], "roles":['Rupert Burns']},
    {"src":'ChrisC', "dst":'BicentennialMan', "type":["DIRECTED"]},
    {"src":'TomH', "dst":'CharlieWilsonsWar', "type":["ACTED_IN"], "roles":['Rep. Charlie Wilson']},
    {"src":'JuliaR', "dst":'CharlieWilsonsWar', "type":["ACTED_IN"], "roles":['Joanne Herring']},
    {"src":'PhilipH', "dst":'CharlieWilsonsWar', "type":["ACTED_IN"], "roles":['Gust Avrakotos']},
    {"src":'MikeN', "dst":'CharlieWilsonsWar', "type":["DIRECTED"]},
    {"src":'TomH', "dst":'ThePolarExpress', "type":["ACTED_IN"], "roles":['Hero Boy', 'Father', 'Conductor', 'Hobo', 'Scrooge', 'Santa Claus']},
    {"src":'RobertZ', "dst":'ThePolarExpress', "type":["DIRECTED"]},
    {"src":'TomH', "dst":'ALeagueofTheirOwn', "type":["ACTED_IN"], "roles":['Jimmy Dugan']},
    {"src":'GeenaD', "dst":'ALeagueofTheirOwn', "type":["ACTED_IN"], "roles":['Dottie Hinson']},
    {"src":'LoriP', "dst":'ALeagueofTheirOwn', "type":["ACTED_IN"], "roles":['Kit Keller']},
    {"src":'RosieO', "dst":'ALeagueofTheirOwn', "type":["ACTED_IN"], "roles":['Doris Murphy']},
    {"src":'Madonna', "dst":'ALeagueofTheirOwn', "type":["ACTED_IN"], "roles":['"All the Way" Mae Mordabito']},
    {"src":'BillPax', "dst":'ALeagueofTheirOwn', "type":["ACTED_IN"], "roles":['Bob Hinson']},
    {"src":'PennyM', "dst":'ALeagueofTheirOwn', "type":["DIRECTED"]},
    {"src":'JamesThompson', "dst":'JessicaThompson', "type":["FOLLOWS"]},
    {"src":'AngelaScope', "dst":'JessicaThompson', "type":["FOLLOWS"]},
    {"src":'PaulBlythe', "dst":'AngelaScope', "type":["FOLLOWS"]},
    {"src":'JessicaThompson', "dst":'CloudAtlas', "type":["REVIEWED"], "summary":'An amazing journey', "rating":95},
    {"src":'JessicaThompson', "dst":'TheReplacements', "type":["REVIEWED"], "summary":'Silly, but fun', "rating":65},
    {"src":'JamesThompson', "dst":'TheReplacements', "type":["REVIEWED"], "summary":'The coolest football movie ever', "rating":100},
    {"src":'AngelaScope', "dst":'TheReplacements', "type":["REVIEWED"], "summary":'Pretty funny at times', "rating":62},
    {"src":'JessicaThompson', "dst":'Unforgiven', "type":["REVIEWED"], "summary":'Dark, but compelling', "rating":85},
    {"src":'JessicaThompson', "dst":'TheBirdcage', "type":["REVIEWED"], "summary":"Slapstick redeemed only by the Robin Williams and Gene Hackman's stellar performances", "rating":45},
    {"src":'JessicaThompson', "dst":'TheDaVinciCode', "type":["REVIEWED"], "summary":'A solid romp', "rating":68},
    {"src":'JamesThompson', "dst":'TheDaVinciCode', "type":["REVIEWED"], "summary":'Fun, but a little far fetched', "rating":65},
    {"src":'JessicaThompson', "dst":'JerryMaguire', "type":["REVIEWED"], "summary":'You had me at Jerry', "rating":92}
]

v = spark.createDataFrame(nodes)
#v.filter("label[0]='Person'").show()
#v.filter("label[0]='MOVIE'").show()
#v.show()
#v.printSchema()

e = spark.createDataFrame(edges)
#e.show()
#e.printSchema()

g = GraphFrame(v, e)
g.vertices.show()
g.edges.show()
g.inDegrees.show()

motifs = g.find("(source)-[rel]->(target)") \
          .filter("target.name = 'The Matrix'")
motifs.show(20, False)
